# Generated by Django 5.2.10 on 2026-01-13 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('developer', models.CharField(blank=True, max_length=200, null=True)),
                ('critic_score', models.FloatField(blank=True, null=True)),
                ('critic_count', models.IntegerField(blank=True, null=True)),
                ('user_score', models.FloatField(blank=True, null=True)),
                ('user_count', models.IntegerField(blank=True, null=True)),
                ('age_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.agerating')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='catalog.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='catalog.platform')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='catalog.publisher')),
            ],
            options={
                'unique_together': {('name', 'platform', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_millions', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='catalog.game')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.region')),
            ],
            options={
                'unique_together': {('game', 'region')},
            },
        ),
    ]
